---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.mongodb.image }}:{{ .Values.mongodb.tag }}
        env:
        - name: MONGO_INITDB_DATABASE
          value: {{ .Values.mongodb.env.database }}
        - name: MONGO_INITDB_ROOT_USERNAME
          value: {{ .Values.mongodb.env.user }}
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: {{ .Values.mongodb.env.password }}
        ports:
        - containerPort: 27017
        - containerPort: 27018
        - containerPort: 27019
        volumeMounts:
        - mountPath: /data/db
          name: datadb
      volumes:
      - name: datadb
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-mongo-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mongo-pvc
spec:
{{- if .Values.persistentVolume.mongo.storageclass }}
  storageClassName: {{ .Values.persistentVolume.mongo.storageclass }}
{{- end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi          
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb-service
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongodb-port-27017
  - port: 27018
    targetPort: 27018
    protocol: TCP
    name: mongodb-port-27018
  - port: 27019
    targetPort: 27019
    protocol: TCP
    name: mongodb-port-27019
  selector:
    app: mongodb
  type: ClusterIP
---
{{- if .Values.security.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-mongodb-from-topo
spec:
  podSelector:
    matchLabels:
      app: mongodb
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: toposervice
    ports:
    - port: 27017
      protocol: TCP
{{- end }}