{{- $persistentVolume := .Values.persistentVolume.enabled -}}
{{- if or $persistentVolume (not (hasKey .Values.persistentVolume "enabled")) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-mysql-pv
spec:
  storageClassName: {{ .Values.persistentVolume.mysql.storageclass }}
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: {{ .Values.persistentVolume.mysql.path }}
{{- end }}