{{- if .Values.persistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-mysql-pv
# {{- if .Values.persistentVolume.storageclass.isPureDefault }}
#   annotations:
#     storageclass.kubernetes.io/is-default-class: true
# {{- end }}
spec:
{{- if not .Values.persistentVolume.storageclass.isPureDefault }}
  storageClassName: mysql
{{- end }}
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /db/mysql
{{- end }}