---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-planner-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: planner
  replicas: 1
  template:
    metadata:
      labels:
        app: planner
        dns-policy: enabled
    spec:
      securityContext:
        runAsUser: 1001
      restartPolicy: Always
      containers:
      - name: planner
        image: {{ .Values.planner.image }}:{{ .Values.planner.tag }}
        env:
        - name: TOPO_HOST
          value: {{ .Release.Name }}-toposervice-service
        - name: TOPO_PORT
          value: {{ .Values.toposervice.ports.containerPort | quote }}
        - name: GRPC_CLIENT_WEATHERSERVER_ADDRESS
          value: static://{{ .Release.Name }}-weatherservice-service:{{ .Values.weatherservice.env.port }}
        - name: SPRING_CLOUD_STREAM_RABBIT_BINDER_NODES
          value: rabbitmq-service:5672
        - name: SPRING_RABBITMQ_HOST
          value: {{ .Release.Name }}-rabbitmq-service
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          value: {{ .Values.rabbitmq.env.defaultUser }}
        - name: SPRING_RABBITMQ_PASSWORD
          value: {{ .Values.rabbitmq.env.defaultPass }}
---
{{- if .Values.security.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-planner-to-rabbit-weather-topo
spec:
  podSelector:
    matchLabels:
      app: planner
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: rabbitmq
    ports:
    - port: 5672
      protocol: TCP
  - to:
    - podSelector:
        matchLabels:
          app: weatherservice
    ports:
    - port: {{ .Values.weatherservice.env.port }}
      protocol: TCP
  - to:
    - podSelector:
        matchLabels:
          app: toposervice
    ports:
    - port: {{ .Values.toposervice.ports.containerPort }}
      protocol: TCP
{{- end -}}