---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-rabbitmq-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.9-management
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: root
        - name: RABBITMQ_DEFAULT_PASS
          value: password
        ports:
        - containerPort: 5672
        - containerPort: 15672
        volumeMounts:
        - mountPath: /var/lib/rabbitmq/mnesia
          name: datarabbit
      volumes:
      - name: datarabbit
        persistentVolumeClaim:
          claimName: rabbit-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-rabbit-pvc
spec:
# {{- if not .Values.persistentVolume.enabled -}}
# {{- $storageClass := .Values.persistentVolume.storageclass.rabbit -}}
#   storageClassName: {{ $storageClass }} #rabbit
# {{- else -}}
# {{- if .Values.persistentVolume.storageclass.isPureDefault -}}
#   annotations:
#     storageclass.kubernetes.io/is-default-class: true
# {{- end -}}
# {{- end -}}
{{- if not .Values.persistentVolume.enabled -}}
  storageClassName: {{ .Values.persistentVolume.storageclass.rabbit }} #rabbit
{{- end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rabbitmq-service
  labels:
    app: rabbitmq
spec:
  ports:
  - port: 5672
    targetPort: 5672
    protocol: TCP
    name: rabbitmq-port-5672
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: rabbitmq-port-15672
  selector:
    app: rabbitmq
  type: ClusterIP
---
{{- if .Values.security.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-rabbitmq-from-planner-server
spec:
  podSelector:
    matchLabels:
      app: rabbitmq
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: planner
    - podSelector:
        matchLabels:
          app: server
    ports:
    - port: 5672
      protocol: TCP
{{- end -}}