---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: server
  replicas: 1
  template:
    metadata:
      labels:
        app: server
        dns-policy: enabled
    spec:
      securityContext:
        runAsUser: 1001
      restartPolicy: Always
      containers:
      - name: server
        image: {{ .Values.server.image }}:{{ .Values.server.tag }}
        command: ["bash"]
        args:
        - "-c"
        - "./wait-for-it.sh {{ .Release.Name }}-mysql-service:3306 -t 20 -- ./wait-for-it.sh {{ .Release.Name }}-rabbitmq-service:5672 -t 20 -- node src/server.js"
        env:
        - name: MYSQL_HOST
          value: {{ .Release.Name }}-mysql-service
        - name: MYSQL_DB
          value: {{ .Values.mysql.env.database }}
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASS
          value: {{ .Values.mysql.env.password }}
        - name: RABBITMQ_URL
          value: amqp://{{ .Values.rabbitmq.env.defaultUser }}:{{ .Values.rabbitmq.env.defaultPass }}@{{ .Release.Name }}-rabbitmq-service
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server-service
  labels:
    app: server
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: server-port
  selector:
    app: server
{{- if .Values.ingress.enabled }}
  type: ClusterIP
{{- else }}
  type: {{ .Values.service.type }}
{{ end }}
---
{{- if .Values.security.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-server-to-mysql-rabbit
spec:
  podSelector:
    matchLabels:
      app: server
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: mysql
    ports:
    - port: 3306
      protocol: TCP
  - to:
    - podSelector:
        matchLabels:
          app: rabbitmq
    ports:
    - port: 5672
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-server-from-ingress
spec:
  podSelector:
    matchLabels:
      app: server
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: ingress-nginx
        podSelector:
          matchLabels:
            app.kubernetes.io/name: ingress-nginx
      ports:
      - protocol: TCP
        port: 3000
{{- end -}}