---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-toposervice-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: toposervice
  replicas: 1
  template:
    metadata:
      labels:
        app: toposervice
        dns-policy: enabled
    spec:
      securityContext:
        runAsUser: 1001
      restartPolicy: Always
      containers:
      - name: toposervice
        image: {{ .Values.toposervice.image }}:{{ .Values.toposervice.tag }}
        env:
        - name: SPRING_DATA_MONGODB_HOST
          value: {{ .Release.Name }}-mongodb-service
        - name: SPRING_DATA_MONGODB_PORT
          value: "27017"
        - name: SPRING_DATA_MONGODB_DATABASE
          value: {{ .Values.mongodb.env.database }}
        - name: SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE
          value: admin
        - name: SPRING_DATA_MONGODB_USERNAME
          value: {{ .Values.mongodb.env.user }}
        - name: SPRING_DATA_MONGODB_PASSWORD
          value: {{ .Values.mongodb.env.password }}
        ports:
        - containerPort: {{ .Values.toposervice.ports.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-toposervice-service
  labels:
    app: toposervice
spec:
  ports:
  - port: {{ .Values.toposervice.ports.containerPort }}
    targetPort: {{ .Values.toposervice.ports.containerPort }}
    protocol: TCP
    name: topo-port
  selector:
    app: toposervice
{{- if .Values.ingress.enabled }}
  type: ClusterIP
{{- else }}
  type: {{ .Values.service.type }}
{{ end }}
---
{{- if .Values.security.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-topo-to-mongodb
spec:
  podSelector:
    matchLabels:
      app: toposervice
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: mongodb
    ports:
    - port: 27017
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-topo-from-planner-ingress
spec:
  podSelector:
    matchLabels:
      app: toposervice
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: planner
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
    ports:
    - protocol: TCP
      port: {{ .Values.toposervice.ports.containerPort }}
{{- end -}}