---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-weatherservice-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: weatherservice
  replicas: 1
  template:
    metadata:
      labels:
        app: weatherservice
    spec:
      securityContext:
        runAsUser: 1001
      restartPolicy: Always
      containers:
      - name: weatherservice
        image: {{ .Values.weatherservice.image }}:{{ .Values.weatherservice.tag }}
        env:
        - name: GRPC_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: GRPC_PORT
          value: {{ .Values.weatherservice.env.port | quote }}
        ports:
        - containerPort: {{ .Values.weatherservice.env.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-weatherservice-service
  labels:
    app: weatherservice
spec:
  ports:
  - port: {{ .Values.weatherservice.env.port }}
    targetPort: {{ .Values.weatherservice.env.port }}
    protocol: TCP
    name: weatherservice-port
  selector:
    app: weatherservice
  type: ClusterIP
---
{{- if .Values.security.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-weather-from-planner
spec:
  podSelector:
    matchLabels:
      app: weatherservice
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: planner
    ports:
    - port: {{ .Values.weatherservice.env.port }}
      protocol: TCP
{{- end -}}